// let myAge:number = 19;
// let myName:string = "talha khan ";
// let isJobless:boolean  = true;
// console.log(myAge,myName,isJobless);
// console.log( myName.toUpperCase);
//  var Class:number = 23;
//  console.log(Class.toExponential());
var nAme = " Talha ";
var Age = 33;
var isworking = false;
console.log(nAme, Age, isworking);
